server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
  main:
    web-application-type: reactive
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: item-service
          uri: lb://item-service
          predicates:
            - Path=/items/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/addresses/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: trade-service
          uri: lb://trade-service
          predicates:
            - Path=/orders/**
        - id: pay-service
          uri: lb://pay-service
          predicates:
            - Path=/pay-orders/**
      httpclient:
        connect-timeout: 5000
        response-timeout: 60s
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
hm:
  gateway:
    jwt:
      location: classpath:hmall.jks
      alias: hmall
      password: hmall123
      tokenTTL: 30m
    auth:
      excludePaths:
        - /search/**
        - /users/login
        - /items/**
        - /hi
        - /hello
