server:
  port: 8080
hm:
  gateway:
    jwt:
      location: classpath:hmall.jks
      alias: hmall
      password: hmall123
      tokenTTL: 30m
    auth:
      excludePaths:
        - /search/**
        - /users/login
        - /items/**
        - /hi
        - /hello
