server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        ip: 192.168.56.1
    sentinel:
      transport:
        dashboard: 127.0.0.1:8090
      http-method-specify: true
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-cart
    port: 33099
    username: root
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.hmall.cart.controller